version: "3.0"
services:

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    image: react
    ports:
      - 3000:3000

  nest:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest
    networks:
      - postgres
    ports:
      - 9633:9633
    depends_on:
      - db

  db:
    image: postgres:14-alpine3.15
    container_name: db
    env_file:
      - ./.env
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    env_file:
      - ./.env
    ports:
      - 5050:80
    networks:
      - postgres
    depends_on:
      - db

volumes:
  postgres:

networks:
  postgres:
